### ISSUE TITLE
FE 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by m-dzn** [m-dzn/VIA#40]
## Todo List
- [x] CNA (Create next-app) 로 Next.js 세팅
- [x] 스타일링 라이브러리 설치 : emotion
- [x] Babel 설정
- [x] 절대 경로 import 설정 : tsconfig.json
- [x] ESLint 설정 : Airbnb
- [x] react-hook-form 세팅

### Babel
1. .babelrc 설정 ([Link](https://nextjs.org/docs/advanced-features/customizing-babel-config))
    1. Next.js : next/babel 프리셋 추가
    2. emotion
        - 프리셋 : "preset-react"에 "@emotion/react" 추가
        - 플러그인 : "@emotion/babel-plugin" 추가

2. tsconfig.json 설정
    > root 경로를 '@/' 로 aliasing 후 import
    ```json
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": ["./*"]
        }
    }
    ```
3. eslint 설정

    git bash 명령어

    ```bash
    $ yarn add -D eslint \
                  @typescript-eslint/parser \
                  @typescript-eslint/eslint-plugin
    ```
    .eslintrc.json 파일

    ```json
    {
       "extends": "next/core-web-vitals"
    }
    ```

## 설정 관련 문서 요약
- Babel 개념
    - Plugin? Babel이 소스 코드를 판단하는 규칙 모음집
      ℹ parsing (소스 to AST) → transformation (AST 변형) → printing (AST to 소스)
      
      따라서 Plugin의 종류도

      a. 문법 플러그인 (parsing)
      b. 변환 플러그인 (transformation)

      으로 나뉩니다.

    - Preset? `정적인 preset` 함께 쓰이는 플러그인들을 세트로 묶어놓은 것
    - preset-env? `동적인 preset` Build 시 어떤 플러그인을 쓸 지 결정할 수 있게 해주는 특수한 preset
    - Polyfill? `런타임 preset` 최신 ECMAScript 코드의 builtIn/method들도 Babel로 처리할 수 있도록 하위 브라우저 지원을 해주는 도구

- ESLint 개념
    > JS 코드의 문법 오류 및 코딩 스타일을 검사 & 에러 표시를 해주는 도구

    설정법
    1. env : 사전 정의된 전역 변수 중 사용할 속성을 true로 설정
    2. globals :  사용자가 커스텀 전역변수를 추가하는 곳 `key-value`
    3. parser : 구문 분석 도구
        - 종류 : "babel-eslint", "@typescript-eslint/parser"
    4. parserOptions : 지원하고 싶은 JS 버전 명시 `default: ES5`
    5. processor : 다른 형식의 파일에서 JS 코드를 추출 후 Lint를 수행하는 pre- 또는 post-processor 등록
    6. plugin : 서드파티 플러그인 등록
        - 축약 : 플러그인 prefix 중 `eslint-plugin-`을 생략할 수 있음
    7. extends : 추가한 플러그인에서 사용할 규칙을 가져와 설정
        - "eslint:all" → 매우 엄격한 규칙 적용
        - "eslint:recommended" → default, 권장 규칙 세트
    8. rules : 개별 규칙 설정
        - 기존 기능을 "off", "warn", "error" 로 설정 가능
        - 추가 옵션은 배열을 써서 설정 가능
